lib/l10n/intl_zh_TW.arb

Update Chinese Traditional

---

lib/l10n/intl_zh_TW.arb

Update Chinese Traditional Translation

---

.github/FAQ.md
.github/README_en.md
README.md

弄了一个应该挺好看的 contributor chart，希望因此被打扰的各位不要把我打死 \_(:з)∠)_
另外，下个版本更新的时候换换预览图？😏

Docs update

---

lib/l10n/intl_zh_TW.arb

Update translation of Chinese Traditional

---

lib/l10n/intl_zh_TW.arb

Update zh-TW Translation

---

lib/l10n/intl_zh_TW.arb

Update translation for Traditional Chinese

---

android/app/src/main/res/values-zh-rTW/strings.xml

Updated legacy translation for Traditional Chinese

---

lib/component/illust_card.dart
lib/component/star_icon.dart
lib/constants.dart
lib/page/picture/illust_lighting_page.dart
lib/page/picture/illust_store.dart
lib/page/soup/soup_page.dart
lib/page/zoom/photo_viewer_page.dart
pubspec.lock
pubspec.yaml

-支持大图加载进度
-支持分享当前已加载完成的图片
-修复亮点的收藏问题
-starIcon去mobx化

Photo view

---

lib/l10n/intl_zh_TW.arb

Update Translation for zh-TW

---

lib/component/illust_card.dart
lib/page/picture/tag_for_illust_page.dart

Star of Card add long press action,  similar to the details page.

---

lib/component/illust_card.dart
lib/component/star_icon.dart

improve layout of illust_card

---

lib/page/hello/setting/setting_quality_page.dart
lib/page/picture/illust_lighting_page.dart
lib/page/picture/illust_row_page.dart
lib/page/zoom/photo_zoom_page.dart
lib/store/save_store.dart
lib/store/user_setting.dart

Download feature

---

lib/l10n/intl_ja.arb

Translated the untranslated text.
Thank you for continuing to maintain the app.
So much easier to use than the official app, one of my favorites! 😻

Update japanese translation

---

lib/l10n/intl_en.arb
lib/l10n/intl_en_US.arb
lib/l10n/intl_es.arb
lib/l10n/intl_ja.arb
lib/l10n/intl_ko.arb
lib/l10n/intl_ru.arb
lib/l10n/intl_tr.arb
lib/l10n/intl_zh.arb
lib/l10n/intl_zh_CN.arb
lib/l10n/intl_zh_TW.arb
lib/models/illust.dart
lib/models/task_persist.dart
lib/page/hello/setting/save_eval_page.dart
lib/page/picture/illust_detail_body.dart
lib/page/picture/illust_lighting_page.dart
lib/page/picture/illust_row_page.dart
lib/page/user/users_page.dart

add AI-generated illust detection

---

lib/l10n/intl_en.arb
lib/l10n/intl_en_US.arb
lib/l10n/intl_es.arb
lib/l10n/intl_ja.arb
lib/l10n/intl_ko.arb
lib/l10n/intl_ru.arb
lib/l10n/intl_tr.arb
lib/l10n/intl_zh.arb
lib/l10n/intl_zh_CN.arb
lib/l10n/intl_zh_TW.arb
lib/models/novel_recom_response.dart
lib/page/hello/ranking/rank_page.dart
lib/page/hello/ranking/rank_store.dart
lib/page/novel/rank/novel_rank_page.dart
lib/page/novel/viewer/novel_viewer.dart

novel AI-gen detect and AI works ranking

---

lib/constants.dart
lib/fluentui.dart
lib/lighting/fluent_lighting_page.dart
lib/main.dart
lib/page/fluent/hello/ranking/rank_page.dart
lib/page/fluent/login/login_page.dart
lib/page/fluent/theme/theme_page.dart

修复了Windows版的一些问题

---

lib/component/fluent/illust_card.dart
lib/component/fluent/painer_card.dart
lib/page/fluent/hello/recom/recom_spotlight_page.dart
lib/page/fluent/hello/setting/setting_cross_adapter_page.dart
lib/page/fluent/history/history_page.dart
lib/page/fluent/painter/painter_list.dart
lib/page/fluent/picture/illust_items_page.dart
lib/page/fluent/picture/illust_row_page.dart
lib/page/fluent/picture/illust_vertical_page.dart
lib/page/fluent/picture/picture_list_page.dart
lib/page/fluent/picture/row_card.dart
lib/page/fluent/picture/tag_for_illust_page.dart
lib/page/fluent/picture/ugoira_loader.dart
lib/page/fluent/platform/platform_page.dart
lib/page/fluent/search/result_illust_list.dart
lib/page/fluent/user/users_page.dart
lib/page/fluent/zoom/photo_zoom_page.dart
lib/page/fluent/zoom/zoom_page.dart
lib/page/hello/fluent_hello_page.dart
lib/platform/windows/saver.dart
pubspec.lock
pubspec.yaml

- ⬆️ 升级依赖项 (bd8489b19dac25dd3aa473cbe599211d208aec79、 979ac8997a8ae27aa72e3ee03fedc14e04a871ec)
- [🔥 移除不该显示的页面的入口](https://github.com/Notsfsssf/pixez-flutter/commit/084426bb3d7b7d5a0a5e35b7a9bd46ef3081e358)
- [🔥 加深所有右键菜单的颜色](https://github.com/Notsfsssf/pixez-flutter/commit/c5cbd0829a63839a541a8253d282eff31af79228)
- [🐛 修复了动图显示不正常的BUG](https://github.com/Notsfsssf/pixez-flutter/commit/47b5318751e070a9f035ad853f6bd7d18b6034b5)
- [♻️ 优化后退体验](https://github.com/Notsfsssf/pixez-flutter/pull/568/commits/165a1ea1dc6637f36ca3482a5f29e5be53400e7b)
- [💄 调整 "关注的作者" 页面](https://github.com/Notsfsssf/pixez-flutter/commit/c35398d6613a442bebcceeb335e9028b6e5463b8)
- [💄 调整 收藏标签 页面](https://github.com/Notsfsssf/pixez-flutter/pull/568/commits/6304cf5477d84b36094da454a7860777c8fcc290)
- [💄 调整 亮点 …

:sparkles: 修复若干问题

---

lib/component/fluent/pixez_button.dart
lib/component/fluent/search_box.dart
lib/component/fluent/sort_group.dart
lib/fluentui.dart
lib/page/Init/guide_page.dart
lib/page/Init/init_page.dart
lib/page/about/languages.dart
lib/page/fluent/Init/guide_page.dart
lib/page/fluent/Init/init_page.dart
lib/page/fluent/account/edit/account_edit_page.dart
lib/page/fluent/account/select/account_select_page.dart
lib/page/fluent/book/tag/book_tag_page.dart
lib/page/fluent/hello/setting/setting_page.dart
lib/page/fluent/hello/setting/setting_quality_page.dart
lib/page/fluent/history/history_page.dart
lib/page/fluent/network/network_setting_page.dart
lib/page/fluent/picture/illust_items_page.dart
lib/page/fluent/shield/shield_page.dart
lib/page/fluent/task/job_page.dart
lib/page/fluent/theme/theme_page.dart
lib/page/hello/fluent_hello_page.dart
lib/page/hello/setting/setting_quality_page.dart
lib/store/user_setting.dart

:sparkles: 调整了设置页面和搜索框

---

lib/component/fluent/painter_avatar.dart
lib/component/fluent/search_box.dart
lib/fluentui.dart
lib/page/fluent/hello/ranking/rank_page.dart
lib/page/fluent/user/users_page.dart
lib/page/hello/fluent_hello_page.dart

[Windows] 修复了几个影响使用的BUG

---

lib/fluentui.dart
lib/page/fluent/hello/recom/recom_spotlight_page.dart
pubspec.lock
pubspec.yaml

修复NavigationPane背景为黑色的问题

---

lib/main.dart
lib/single_instance_plugin.dart
windows/runner/SingleInstance.cpp

:ambulance: 修复了单例 EventChannel 不能工作的问题

---

lib/constants.dart
lib/fluent/component/ban_page.dart
lib/fluent/component/illust_card.dart
lib/fluent/component/search_box.dart
lib/fluent/lighting/fluent_lighting_page.dart
lib/fluent/page/directory/save_mode_choice_page.dart
lib/fluent/page/hello/recom/recom_spotlight_page.dart
lib/fluent/page/painter/painter_list.dart
lib/fluent/page/picture/illust_detail_body.dart
lib/fluent/page/picture/illust_items_page.dart
lib/fluent/page/picture/illust_row_page.dart
lib/fluent/page/picture/illust_vertical_page.dart
lib/fluent/page/preview/preview_page.dart
lib/fluent/page/spotlight/spotlight_page.dart
lib/fluent/page/task/job_page.dart
lib/fluent/utils.dart
lib/lighting/lighting_store.dart
lib/page/hello/recom/spotlight_store.dart
lib/page/painter/painter_list_store.dart
lib/page/picture/illust_about_store.dart
lib/utils.dart
pubspec.lock
pubspec.yaml

目前的PixEz(for Windows)的列表懒加载有点懒过头了（指压根不加载）
在这个PR中将会尝试修复这个问题

[Windows] 懒加载优化

---

lib/fluent/page/account/edit/account_edit_page.dart
lib/fluent/page/login/login_page.dart
lib/fluent/page/login/token_page.dart
pubspec.lock
pubspec.yaml

- 8f32bf742ad9b897cac2aae28ad71a2a323159f4 现在它可以导出 Token 和通过 Token 登录了

为 Fluent UI 添加一个小功能

---

lib/fluent/page/about/about_page.dart
lib/fluent/page/comment/comment_page.dart
lib/fluent/page/hello/new/illust/new_illust_page.dart
lib/page/about/contributors.dart
pubspec.yaml

用 MenuFlyout 和 showDialog 平替(?

修复了 最新版 fluent_ui 没有 showBottomSheet 的问题

---

lib/fluent/component/illust_card.dart
lib/fluent/page/comment/comment_page.dart
lib/fluent/page/hello/new/illust/new_illust_page.dart
lib/fluent/page/history/history_page.dart
lib/fluent/page/picture/illust_detail_body.dart
lib/fluent/page/picture/illust_items_page.dart
lib/fluent/page/picture/row_card.dart
lib/fluent/page/picture/ugoira_loader.dart
lib/fluent/page/user/users_page.dart
lib/fluent/page/zoom/photo_zoom_page.dart
windows/flutter/CMakeLists.txt

偶尔动一下表示PixEz还有Windows支持
~~虽然并没有积极维护~~

修复会使右键菜单关闭当前页面的BUG

---

lib/fluent/component/illust_card.dart
lib/fluent/page/hello/fluent_hello_page.dart

Windows桌面UI添加用 Alt + ← 后退的快捷键

---

.metadata
.vscode/launch.json
lib/clipboard_plugin.dart
lib/fluent/component/illust_card.dart
lib/fluent/page/network/network_page.dart
lib/fluent/page/picture/illust_items_page.dart
lib/fluent/page/zoom/photo_zoom_page.dart
lib/page/zoom/photo_zoom_page.dart
windows/runner/CMakeLists.txt
windows/runner/Clipboard.cpp
windows/runner/Clipboard.h
windows/runner/flutter_window.cpp

只实现了 Windows 平台的 MethodChannel ，所以是 Windows Only 的

直接将图片复制到剪贴板

---

windows/CMakeLists.txt

Reverts Notsfsssf/pixez-flutter#710
对 @BTMuli 的努力来一波全盘否定
#712 也不用合了
Close #712

Revert "👷 update sqlite3 cmake build"

---

lib/page/theme/theme_page.dart

fix theme page

---

.github/README_id.md

Just wanting to add some Indonesian translation for README section.

Adding Indonesian README translation

---

lib/page/theme/theme_page.dart

修复了.toString()在debug和release下表现不一致导致的问题x

fix theme_page

---

lib/er/fluent_leader.dart
lib/fluent/component/pixez_global_shortkey_listener.dart
lib/fluent/component/search_box/item.dart
lib/fluent/component/search_box/pixez_search_box.dart
lib/fluent/fluentui.dart
lib/fluent/navigation/pixez_page_history_manager.dart
lib/fluent/page/follow/follow_list.dart
lib/fluent/page/hello/fluent_hello_page.dart
lib/fluent/page/hello/new/illust/new_illust_page.dart
lib/fluent/page/hello/setting/setting_quality_page.dart
lib/fluent/page/user/bookmark/bookmark_page.dart
lib/fluent/page/user/users_page.dart
lib/fluent/platform/platform.dart
pubspec.lock
pubspec.yaml
windows/runner/CMakeLists.txt
windows/runner/SingleInstance.h

- d051dc65ca14c03e820976a264317bcb9be6caf1 一个积压的 不算特别重要的提交
- 60e60478a0f591715e09aceb4cc3a05af9e4c314 升级 fluent ui 依赖项
- a2aecd26eb9cc5fe942d7acfebaf86ed64caece1 重写 fluent ui 的初始化部分
- 80d18c6a9589410af17bab1e5833fe6f271208a3 重写 hello page，现在能够保留状态了

Windows 支持更新

---

assets/json/host.json
lib/er/hoster.dart
lib/network/account_client.dart
lib/network/api_client.dart
lib/network/oauth_client.dart

Fix https://github.com/Notsfsssf/pixez-flutter/issues/845

Fix 421 error

---

lib/fluent/page/network/network_setting_page.dart
lib/page/network/network_setting_page.dart

pximg 更换了 ip 段，现在整个 210.140.92.0/24 已停止使用

Update pximg ip

---

.github/workflows/build_windows.yml
.metadata
lib/fluent/component/pixez_button.dart
lib/fluent/component/search_box/pixez_search_box.dart
lib/fluent/component/selectable_html.dart
lib/fluent/page/hello/recom/recom_spotlight_page.dart
lib/fluent/page/hello/recom/recom_user_road.dart
lib/fluent/page/network/network_setting_page.dart
lib/fluent/page/picture/illust_items_page.dart
lib/fluent/page/report/report_items_page.dart
lib/fluent/page/theme/theme_page.dart
lib/fluent/page/user/users_page.dart

添加 Windows CI

---

lib/component/illust_card.dart
lib/component/pixiv_image_shielded.dart
lib/constants.dart
lib/fluent/component/illust_card.dart
lib/page/about/contributors.dart

修复所有的 'assets/images/h.jpg'
还是塞个常量好了

修复所有的 h.jpg 路径

---

.github/README_en.md
.github/README_id.md
README.md

更新下载地址
顺便在这里清理一个 Issues
Close #950

更新 README.md 下载地址 

---

lib/l10n/intl_en.arb
lib/l10n/intl_en_US.arb
lib/l10n/intl_es.arb
lib/l10n/intl_id.arb
lib/l10n/intl_id_ID.arb
lib/l10n/intl_ja.arb
lib/l10n/intl_ko.arb
lib/l10n/intl_ru.arb
lib/l10n/intl_tr.arb
lib/l10n/intl_zh.arb
lib/l10n/intl_zh_CN.arb
lib/l10n/intl_zh_TW.arb
lib/page/hello/setting/data_export_page.dart
lib/page/hello/setting/save_format_page.dart

支持对小说历史进行导出等
